export const MARKERS = {
             yellow: "//maps.google.com/mapfiles/ms/micons/yellow.png",
         yellow_dot: "//maps.google.com/mapfiles/ms/micons/yellow-dot.png",
               blue: "//maps.google.com/mapfiles/ms/micons/blue.png",
           blue_dot: "//maps.google.com/mapfiles/ms/micons/blue-dot.png",
              green: "//maps.google.com/mapfiles/ms/micons/green.png",
          green_dot: "//maps.google.com/mapfiles/ms/micons/green-dot.png",
          lightblue: "//maps.google.com/mapfiles/ms/micons/lightblue.png",
      lightblue_dot: "//maps.google.com/mapfiles/ms/micons/ltblue-dot.png",
             orange: "//maps.google.com/mapfiles/ms/micons/orange.png",
         orange_dot: "//maps.google.com/mapfiles/ms/micons/orange-dot.png",
               pink: "//maps.google.com/mapfiles/ms/micons/pink.png",
           pink_dot: "//maps.google.com/mapfiles/ms/micons/pink-dot.png",
             purple: "//maps.google.com/mapfiles/ms/micons/purple.png",
         purple_dot: "//maps.google.com/mapfiles/ms/micons/purple-dot.png",
                red: "//maps.google.com/mapfiles/ms/micons/red.png",
            red_dot: "//maps.google.com/mapfiles/ms/micons/red-dot.png",
     yellow_pushpin: "//maps.google.com/mapfiles/ms/micons/ylw-pushpin.png",
       blue_pushpin: "//maps.google.com/mapfiles/ms/micons/blue-pushpin.png",
      green_pushpin: "//maps.google.com/mapfiles/ms/micons/grn-pushpin.png",
  lightblue_pushpin: "//maps.google.com/mapfiles/ms/micons/ltblu-pushpin.png",
       pink_pushpin: "//maps.google.com/mapfiles/ms/micons/pink-pushpin.png",
     purple_pushpin: "//maps.google.com/mapfiles/ms/micons/purple-pushpin.png",
        red_pushpin: "//maps.google.com/mapfiles/ms/micons/red-pushpin.png",
};

