export const MARKERS = {
             yellow: "http://maps.google.com/mapfiles/ms/micons/yellow.png",
         yellow_dot: "http://maps.google.com/mapfiles/ms/micons/yellow-dot.png",
               blue: "http://maps.google.com/mapfiles/ms/micons/blue.png",
           blue_dot: "http://maps.google.com/mapfiles/ms/micons/blue-dot.png",
              green: "http://maps.google.com/mapfiles/ms/micons/green.png",
          green_dot: "http://maps.google.com/mapfiles/ms/micons/green-dot.png",
          lightblue: "http://maps.google.com/mapfiles/ms/micons/lightblue.png",
      lightblue_dot: "http://maps.google.com/mapfiles/ms/micons/ltblue-dot.png",
             orange: "http://maps.google.com/mapfiles/ms/micons/orange.png",
         orange_dot: "http://maps.google.com/mapfiles/ms/micons/orange-dot.png",
               pink: "http://maps.google.com/mapfiles/ms/micons/pink.png",
           pink_dot: "http://maps.google.com/mapfiles/ms/micons/pink-dot.png",
             purple: "http://maps.google.com/mapfiles/ms/micons/purple.png",
         purple_dot: "http://maps.google.com/mapfiles/ms/micons/purple-dot.png",
                red: "http://maps.google.com/mapfiles/ms/micons/red.png",
            red_dot: "http://maps.google.com/mapfiles/ms/micons/red-dot.png",
     yellow_pushpin: "http://maps.google.com/mapfiles/ms/micons/ylw-pushpin.png",
       blue_pushpin: "http://maps.google.com/mapfiles/ms/micons/blue-pushpin.png",
      green_pushpin: "http://maps.google.com/mapfiles/ms/micons/grn-pushpin.png",
  lightblue_pushpin: "http://maps.google.com/mapfiles/ms/micons/ltblu-pushpin.png",
       pink_pushpin: "http://maps.google.com/mapfiles/ms/micons/pink-pushpin.png",
     purple_pushpin: "http://maps.google.com/mapfiles/ms/micons/purple-pushpin.png",
        red_pushpin: "http://maps.google.com/mapfiles/ms/micons/red-pushpin.png",
};

